# Generated by Django 5.2.7 on 2025-10-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerApplications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
