# Generated by Django 5.2.7 on 2025-11-04 06:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('skills', models.TextField()),
                ('availability', models.BooleanField(default=False)),
                ('date_applied', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
